### ISSUE TITLE
Correction suggestion in Quiz 1

### ISSUE THREAD

**Issue by leabstrait** [wimvanderbauwhede/HaskellMOOC#1]
I am currently taking the Haskell MOOC in futurelearn.

Issue:

In Question 2 of Quiz 1, section 1.5 : (link) https://www.futurelearn.com/courses/functional-programming-haskell/1/steps/71174/questions/2
The instructor response should include the article/section1.3, which deals with 'Precedence of Function Applications' and not the article/section 1.2 Basic Elements By Example which has no mention of function precedence.

And the same thing in Question 4 of Quiz 1, section 1.5 : (link) https://www.futurelearn.com/courses/functional-programming-haskell/1/steps/71174/questions/4
It is section/article 1.3 that deals with immutable names/ variables in Haskell.

**Comment by wimvanderbauwhede** [comment]
Thanks for letting us know, I've fixed it.
